#!/bin/bash
# sync_docs.sh
# Extracts Rust module documentation from the Core crate and synchronizes it with the root README.md

README_PATH="README.md"
CORE_SRC_DIR="v4/crates/core/src"
TEMP_DOCS_FILE="temp_docs.md"

if [ ! -f "$README_PATH" ]; then
    echo "Error: $README_PATH not found."
    exit 1
fi

echo "## Core Modules Documentation" > "$TEMP_DOCS_FILE"
echo "" >> "$TEMP_DOCS_FILE"
echo "Autogenerated from Rust source code (\`$CORE_SRC_DIR\`):" >> "$TEMP_DOCS_FILE"
echo "" >> "$TEMP_DOCS_FILE"

for file in "$CORE_SRC_DIR"/*.rs; do
    module_name=$(basename "$file" .rs)
    
    # Extract lines starting with //! (Rust module-level documentation)
    # Removing the //! prefix and any leading spaces
    doc_content=$(grep -E "^//!" "$file" | sed -E 's|^//! ?||')
    
    if [ ! -z "$doc_content" ]; then
        echo "### \`core::$module_name\`" >> "$TEMP_DOCS_FILE"
        echo "$doc_content" >> "$TEMP_DOCS_FILE"
        echo "" >> "$TEMP_DOCS_FILE"
    else
        # If no module-level doc is found, just list the module name
        echo "### \`core::$module_name\`" >> "$TEMP_DOCS_FILE"
        echo "*(No module-level documentation provided)*" >> "$TEMP_DOCS_FILE"
        echo "" >> "$TEMP_DOCS_FILE"
    fi
done

# We will append or replace the section in README.md
# We use sed to remove anything after "## Core Modules Documentation"
sed -i.bak '/^## Core Modules Documentation/,$d' "$README_PATH"

# Append the new docs to the README
cat "$TEMP_DOCS_FILE" >> "$README_PATH"

# Clean up
rm "$TEMP_DOCS_FILE" "$README_PATH.bak"

echo "Documentation synchronized with $README_PATH successfully."
